### ISSUE TITLE
Public imagery

### ISSUE THREAD

**Issue by guylepage3** [code-creative-co/code-creative#1]
> **Last updated**: Dec 2, 2024

**Description**
Public imagery for GitHub.

**Tasks**
- [ ] Create list of issues & resources.

**Issues & resources**

**Reference(s)**
- [x] [Simple Icons](https://simpleicons.org/)
- [x] [Simpleicons.Vercel.App](https://simpleicons.vercel.app/)

**Comment by guylepage3** [comment]
![lepagebond-github-1128x125](https://user-images.githubusercontent.com/1711854/230803711-2eb39d34-eb87-466c-b97e-ea51bd17d705.png)
![lepagebond-github-rev-1128x125](https://user-images.githubusercontent.com/1711854/230803712-f8bbebb2-7aa1-4165-94c1-051e1894e355.png)

**Comment by guylepage3** [comment]
```
github-lepagebond-banner-1600x170
width="840px"
https://user-images.githubusercontent.com/1711854/232259066-5e853749-e35a-426f-ab76-ee453e435643.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232259066-5e853749-e35a-426f-ab76-ee453e435643.svg" width="840px" alt="Lepage & Bond banner [lepagebond-github-banner-1600x170]">

```
github-lepagebond-banner-rev-1600x170
width="840px"
https://user-images.githubusercontent.com/1711854/232259067-9974924f-ebe1-446d-b50e-193cce55cc04.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232259067-9974924f-ebe1-446d-b50e-193cce55cc04.svg" width="840px" alt="Lepage & Bond banner [lepagebond-github-banner-rev-1600x170]">

**Comment by guylepage3** [comment]
```
github-lepagebond-com-btn-135x28
width="135px"
https://user-images.githubusercontent.com/1711854/232360905-82f1eea9-edb6-4706-9989-ce785ff9b067.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232360905-82f1eea9-edb6-4706-9989-ce785ff9b067.svg" width="135px" alt="lepagebond.com [135x28]">

```
github-lepagebond-com-btn-rev-135x28
width="135px"
https://user-images.githubusercontent.com/1711854/232360906-2d0c1132-44be-4260-b083-c58fc87ccef0.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232360906-2d0c1132-44be-4260-b083-c58fc87ccef0.svg" width="135px" alt="lepagebond.com [135x28]" >

```
github-lepagegrp-com-btn-123x28-light
width="123px"
https://github.com/lepagegrp/lepagebond/assets/1711854/579e3349-7c26-47bd-8967-aba21de8a1ed
```
<img src="https://github.com/lepagegrp/lepagebond/assets/1711854/579e3349-7c26-47bd-8967-aba21de8a1ed" width="123px" alt="lepagegrp.com [123x28]">

```
github-lepagegrp-com-btn-123x28-dark
width="123px"
https://github.com/lepagegrp/lepagebond/assets/1711854/93e899a6-afaa-4c7a-8988-59ff67137959
```
<img src="https://github.com/lepagegrp/lepagebond/assets/1711854/93e899a6-afaa-4c7a-8988-59ff67137959" width="123px" alt="lepagegrp.com [123x28]">

**Comment by guylepage3** [comment]
```
github-twitter-btn-95x28
width="95px"
https://user-images.githubusercontent.com/1711854/232361123-47a91dbe-7bb1-4513-901d-8bffef1521f6.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361123-47a91dbe-7bb1-4513-901d-8bffef1521f6.svg" width="95px" alt="Guy Lepage Twitter [95x28]">

```
github-twitter-btn-rev-95x28
width="95px"
https://user-images.githubusercontent.com/1711854/232361127-ecae2f2a-27c8-49e2-871b-eed7c52da63d.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361127-ecae2f2a-27c8-49e2-871b-eed7c52da63d.svg" width="95px" alt="Guy Lepage Twitter [95x28]" >

----

```
github-instagram-btn-115x28
width="115px"
https://user-images.githubusercontent.com/1711854/232361149-1d4a778d-f353-41b6-8019-ca8c64528708.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361149-1d4a778d-f353-41b6-8019-ca8c64528708.svg" width="115px" alt="Guy Lepage Instagram [115x28]">

```
github-instagram-btn-rev-115x28
width="115px"
https://user-images.githubusercontent.com/1711854/232361150-07f74108-99ce-4344-bf5f-bf76bb18f63e.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361150-07f74108-99ce-4344-bf5f-bf76bb18f63e.svg" width="115px" alt="Guy Lepage Instagram [115x28]" >

**Comment by guylepage3** [comment]
```
github-lepagebond-wiki-banner-1600x70
width="840px"
https://user-images.githubusercontent.com/1711854/232259140-c5050782-08a7-464a-b6bd-c675b9ed8d12.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232259140-c5050782-08a7-464a-b6bd-c675b9ed8d12.svg" width="840px" alt="Lepage & Bond banner [1600x70]">

```
github-lepagebond-wiki-banner-rev-1600x70
width="840px"
https://user-images.githubusercontent.com/1711854/232259141-fc4efbc3-51c8-48f4-8be4-6155a6ca2ce4.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232259141-fc4efbc3-51c8-48f4-8be4-6155a6ca2ce4.svg" width="840px" alt="Lepage & Bond banner [1600x70]">

**Comment by guylepage3** [comment]
```
github-status-production-btn-170x28
width="170px"
https://user-images.githubusercontent.com/1711854/232361455-04318063-7f68-43cd-8641-96a088062522.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361455-04318063-7f68-43cd-8641-96a088062522.svg" width="170px" alt="Production Status [170x28]">

```
github-status-production-passing-btn-178x28
width="178px"
https://user-images.githubusercontent.com/1711854/232361461-feb2ca18-c4d9-4b16-8d77-098f70dc8bc6.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361461-feb2ca18-c4d9-4b16-8d77-098f70dc8bc6.svg" width="178px" alt="Production Passing [178x28]">

```
github-status-production-failing-btn-175x28
width="175px"
https://user-images.githubusercontent.com/1711854/232361458-088a2225-588b-413b-851f-d7c234f3b53b.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361458-088a2225-588b-413b-851f-d7c234f3b53b.svg" width="175px" alt="Production Failing! [175x28]">

**Comment by guylepage3** [comment]
```
github-status-development-ready-btn-174x28
width="174px"
https://user-images.githubusercontent.com/1711854/232361771-f8b7fcdb-0f65-460d-8ed1-b649991b6d1a.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361771-f8b7fcdb-0f65-460d-8ed1-b649991b6d1a.svg" width="174px" alt="Development Ready [174x28]">

```
github-status-development-in-progress-btn-212x28
width="212px"
https://user-images.githubusercontent.com/1711854/232361769-7d724aa2-9a49-4930-a32a-3cee1a7c8bc2.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361769-7d724aa2-9a49-4930-a32a-3cee1a7c8bc2.svg" width="212px" alt="Development In Progress [212x28]">

```
github-status-development-needs-update-btn-225x28
width="225px"
https://user-images.githubusercontent.com/1711854/232361770-59a56117-4fcf-4683-948c-b12b6ca14c22.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361770-59a56117-4fcf-4683-948c-b12b6ca14c22.svg" width="225px" alt="Development Needs Update! [225x28]">

```
github-status-development-failing-btn-184x28
width="184px"
https://user-images.githubusercontent.com/1711854/232361767-a73f16c0-413d-4fa0-a2f2-50d8d228d532.svg
```
<img src="https://user-images.githubusercontent.com/1711854/232361767-a73f16c0-413d-4fa0-a2f2-50d8d228d532.svg" width="184px" alt="Development Failing! [184x28]">

**Comment by guylepage3** [comment]
```
github-lepage-banner-1600x170-light
width="840px"
https://github.com/lepagegrp/lepagebond/assets/1711854/40c1a0d3-b332-49ac-8ce9-3c0461c0dcc2
```
<img src="https://github.com/lepagegrp/lepagebond/assets/1711854/40c1a0d3-b332-49ac-8ce9-3c0461c0dcc2" width="840px" alt="Lepage banner [github-lepage-banner-1600x170-light]">

```
github-lepage-banner-1600x170-dark
width="840px"
https://github.com/lepagegrp/lepagebond/assets/1711854/21fb7810-71df-472b-abe1-6464bc2e0d96
```
<img src="https://github.com/lepagegrp/lepagebond/assets/1711854/21fb7810-71df-472b-abe1-6464bc2e0d96" width="840px" alt="Lepage banner [github-lepage-banner-1600x170-dark]">

```
github-lepage-banner-1600x170-light
width="840px"
https://github.com/lepagegrp/lepagebond/assets/1711854/d81149ee-6a62-44e2-893e-8941f68634c9
```
<img src="https://github.com/lepagegrp/lepagebond/assets/1711854/d81149ee-6a62-44e2-893e-8941f68634c9" width="840px" alt="Lepage banner [github-lepage-banner-1600x170-light]">

```
github-lepage-banner-1600x70-dark
width="840px"
https://github.com/lepagegrp/lepagebond/assets/1711854/4c9a5d01-b39f-4142-a321-69ad01639f30
```
<img src="https://github.com/lepagegrp/lepagebond/assets/1711854/4c9a5d01-b39f-4142-a321-69ad01639f30" width="840px" alt="Lepage banner [github-lepage-banner-1600x70-dark]">
